# Site settings
title: Geo-Replicated, Near Real-Time, Scalable Database
email: openmesadb@gmail.com
description: "MesaDB is inspired by Mesa of Google, it's a Geo-Replicated, Near Real-Time, Scalable Data Warehousing."
baseurl: ""
url: "http://mesadb.com"
twitter_username: openmesadb
github_username:  mesadb

# Build settings
markdown: kramdown
permalink: pretty
