#This file is auto generated by the build script"
dbname          = 'mesadb'
package         = 'mesadb'
PRODUCT_VERSION = r'''X.X.X.X'''
BINARY_NAME     = 'mesadb'
OSSHORTNAME     = r'''RHEL5'''
INSTALL_PREFIX  = r'''/opt/mesadb'''
DEVENV          = False
DOC_CSH_URL_FORMAT = r'''https://my.mesadb.com/docs/%(short_version)s/HTML/index.htm#cshid=%(id)s'''
